// ============================================================
// words.ts — linguistic resources for the Smart Mnemonic Engine
// + a built-in EN→AR glossary for bilingual mode
// ============================================================

/** Concrete, easy, imageable words for each Latin letter. */
export const wordBank: Record<string, string[]> = {
  A: ['Angry', 'Apple', 'Airplane', 'Alligator', 'Amazing', 'Anchor', 'Astronaut', 'Autumn', 'Acrobat', 'Avocado'],
  B: ['Baby', 'Banana', 'Big', 'Bubble', 'Butterfly', 'Bridge', 'Battery', 'Bouncy', 'Blizzard', 'Bottle'],
  C: ['Cat', 'Candy', 'Cloud', 'Crazy', 'Circle', 'Coffee', 'Castle', 'Cucumber', 'Cricket', 'Crayon'],
  D: ['Dancing', 'Dragon', 'Duck', 'Diamond', 'Donut', 'Dolphin', 'Desert', 'Dizzy', 'Door', 'Dynamite'],
  E: ['Elephant', 'Eagle', 'Echo', 'Engine', 'Empty', 'Egg', 'Elf', 'Envelope', 'Earth', 'Energy'],
  F: ['Funny', 'Fire', 'Flower', 'Frog', 'Frozen', 'Feather', 'Fan', 'Fox', 'Fountain', 'Flag'],
  G: ['Giant', 'Guitar', 'Garden', 'Ghost', 'Globe', 'Golden', 'Grape', 'Giraffe', 'Glacier', 'Gadget'],
  H: ['Happy', 'Horse', 'House', 'HOT', 'Honey', 'Horizon', 'Helmet', 'Hurricane', 'Hammer', 'Hippo'],
  I: ['Ice', 'Igloo', 'Ink', 'Island', 'Ivy', 'Illuminated', 'Imagine', 'Iron', 'Icicle', 'Idea'],
  J: ['Jelly', 'Jungle', 'Jumping', 'Jewel', 'Jacket', 'Journey', 'Joker', 'Juice', 'Jet', 'Jam'],
  K: ['King', 'Kitchen', 'Kite', 'Kangaroo', 'Keyboard', 'Kitten', 'Kettle', 'Kite', 'Kind', 'Kiwi'],
  L: ['Little', 'Lion', 'Lantern', 'Lemon', 'Ladder', 'Lagoon', 'Loud', 'Ladybug', 'Lava', 'Library'],
  M: ['Magic', 'Moon', 'Monkey', 'Make', 'Magnet', 'Mountain', 'Melon', 'Muffin', 'Mirror', 'Magnet'],
  N: ['Night', 'Nest', 'Noodle', 'Noble', 'North', 'Nutmeg', 'Neon', 'Ninja', 'Note', 'Navy'],
  O: ['Ocean', 'Orange', 'Owl', 'Open', 'Oasis', 'Octopus', 'Oven', 'Olive', 'Otter', 'Orbit'],
  P: ['Purple', 'Piano', 'Pirate', 'Pizza', 'Panda', 'Pebble', 'Pillow', 'Prism', 'Puzzle', 'Pumpkin'],
  Q: ['Queen', 'Quiet', 'Quilt', 'Question', 'Quartz', 'Quick', 'Quiver', 'Quiz', 'Quail', 'Queue'],
  R: ['Rainbow', 'Rocket', 'Rabbit', 'Ring', 'Rope', 'River', 'Robot', 'Riddle', 'Roast', 'Rug'],
  S: ['Smart', 'Sun', 'Snake', 'Star', 'Stone', 'Spider', 'Silver', 'Sandwich', 'Snow', 'Ship'],
  T: ['Tiger', 'Turtle', 'Table', 'Thunder', 'Tunnel', 'Tulip', 'Taco', 'Torch', 'Train', 'Teddy'],
  U: ['Umbrella', 'Unicorn', 'Unique', 'Universe', 'Under', 'Urban', 'Upbeat', 'UFO', 'Unite', 'Urgent'],
  V: ['Very', 'Volcano', 'Violin', 'Violet', 'Valley', 'Vapor', 'Viking', 'Velvet', 'Vase', 'Vigorous'],
  W: ['Wonderful', 'Whale', 'Water', 'Wind', 'Wizard', 'Window', 'Waffle', 'Wolf', 'Wave', 'Wagon'],
  X: ['Xylophone', 'X-ray', 'Xenon', 'Xerox', 'Xmas', 'Xerus'],
  Y: ['Yellow', 'Yacht', 'Yogurt', 'Yawn', 'Yak', 'Yarn', 'Year', 'Youth', 'Yodel', 'Yacht'],
  Z: ['Zebra', 'Zoom', 'Zigzag', 'Zone', 'Zesty', 'Zero', 'Zoo', 'Zen', 'Zap', 'Zigzag'],
}

/** Words that make a mnemonic stickier (slightly odd / funny / vivid). */
export const oddWords = new Set(
  [
    'Angry', 'Crazy', 'Dizzy', 'Ghost', 'HOT', 'Hurricane', 'Joker', 'Ninja', 'Pirate', 'Quirk',
    'Robot', 'Snake', 'Thunder', 'UFO', 'Wizard', 'Zigzag', 'Zap', 'Zoom', 'Dynamite', 'Blizzard',
    'Alligator', 'Octopus', 'Kangaroo', 'Unicorn', 'Zebra', 'Hippo', 'Giraffe', 'Lava', 'Viking',
    'Rocket', 'Spider', 'Crocodile', 'Banana', 'Taco', 'Waffle', 'Yeti', 'Giant', 'Duck', 'Penguin',
    'Hammer', 'Whale', 'Panda', 'Dragon', 'Monkey', 'Tiger', 'Elephant', 'Puzzle', 'Quiver', 'Yodel',
  ].map((w) => w.toLowerCase()),
)

/** Very high-imageability words (easy to visualize). */
export const imageable = new Set(
  [
    'cat', 'dog', 'sun', 'moon', 'star', 'tree', 'house', 'car', 'bird', 'fish', 'book', 'door',
    'fire', 'water', 'cloud', 'rain', 'snow', 'fish', 'egg', 'eye', 'hand', 'face', 'head', 'king',
    'queen', 'cake', 'ball', 'bell', 'drum', 'ship', 'boat', 'horse', 'mouse', 'wolf', 'bear', 'lion',
    'frog', 'duck', 'bee', 'ant', 'fly', 'cow', 'pig', 'fox', 'owl', 'bat', 'gem', 'coin', 'ring',
    'key', 'lock', 'wall', 'road', 'bridge', 'tower', 'flag', 'crown', 'sword', 'shield', 'rope',
    'ladder', 'window', 'chair', 'table', 'clock', 'mirror', 'candle', 'lantern', 'mountain', 'river',
    'island', 'desert', 'forest', 'garden', 'flower', 'leaf', 'seed', 'apple', 'banana', 'bread',
    'cheese', 'milk', 'honey', 'pizza', 'candy', 'chocolate', 'radio', 'phone', 'camera', 'engine',
    'rocket', 'plane', 'train', 'bike', 'balloon', 'kite', 'puzzle', 'toy', 'mask', 'hat', 'boot',
  ].map((w) => w.toLowerCase()),
)

export const englishStop = new Set([
  'a', 'an', 'the', 'of', 'and', 'or', 'in', 'on', 'at', 'to', 'for', 'is', 'are', 'was', 'were',
  'by', 'with', 'from', 'as', 'be', 'it', 'its', 'this', 'that', 'these', 'those', 'what', 'which',
  'how', 'why', 'when', 'who', 'whom', 'into', 'than', 'then', 'them', 'they', 'we', 'our', 'you',
  'your', 'i', 'my', 'me', 'he', 'she', 'his', 'her', 'not', 'no', 'do', 'does', 'did', 'can',
  'could', 'should', 'would', 'may', 'might', 'must', 'will', 'shall', 'have', 'has', 'had',
])

export const arabicStop = new Set([
  'في', 'من', 'على', 'إلى', 'عن', 'مع', 'هذا', 'هذه', 'ذلك', 'التي', 'الذي', 'و', 'أو', 'ثم',
  'كل', 'بين', 'ما', 'لا', 'أن', 'إن', 'كان', 'كانت', 'هو', 'هي', 'هما', 'هم', 'هن', 'ذلك',
  'كذلك', 'أيضا', 'أيضًا', 'عند', 'حتى', 'لدى', 'بعد', 'قبل', 'خلال', 'ضمن', 'حول', 'عبر',
])

/**
 * Built-in glossary EN → Arabic simple explanation.
 * Used for Bilingual mode (English term + ببساطة explanation).
 * Scoped to common university foundational terms (food science, bio, CS, math, business, physics, chemistry, health).
 */
export const glossary: Record<string, string> = {
  'haccp': 'نظام وقائي لسلامة الغذاء يحدد المخاطر ويتحكم فيها',
  'hazard analysis': 'تحليل المخاطر: دراسة ما قد يسبب مرضًا أو إصابة في الغذاء',
  'critical control point': 'نقطة التحكم الحرجة: خطوة نتحكم فيها لإزالة الخطر',
  'ccp': 'نقطة التحكم الحرجة (Critical Control Point)',
  'critical limits': 'الحدود الحرجة: أرقام محددة (حرارة/زمن) تفصل بين الآمن والخطير',
  'monitoring': 'المراقبة: متابعة دورية للتأكد من الالتزام بالحدود',
  'corrective action': 'الإجراء التصحيحي: ما نفعله عند تجاوز الحد الحرج',
  'verification': 'التحقق: تأكد أن النظام يعمل كما هو مخطط',
  'record keeping': 'حفظ السجلات: توثيق كل خطوة كدليل',
  'pathogen': 'مُمرض: كائن يسبب المرض',
  'bacteria': 'بكتيريا: كائنات مجهرية قد تكون مفيدة أو ضارة',
  'virus': 'فيروس: ينتشر داخل خلايا الجسم ويتكاثر بها',
  'microorganism': 'كائن دقيق: كائن غير مرئي بالعين المجردة',
  'microbiology': 'علم الأحياء الدقيقة: دراسة الكائنات الدقيقة',
  'sterilization': 'تعقيم: إزالة كل الكائنات الحية بما فيها البكتيريا',
  'pasteurization': 'بسترة: تسخين لقتل الممرضات مع الحفاظ على الخواص',
  'fermentation': 'تخمر: تحول السكريات بفعل الكائنات الدقيقة',
  'enzyme': 'إنزيم: بروتين يسرع التفاعلات الحيوية',
  'protein': 'بروتين: بناء الجسم ووظائفه الأساسية',
  'carbohydrate': 'كربوهيدرات: مصدر الطاقة الرئيسي',
  'lipid': 'دهون: تحفظ الطاقة وتذيب الفيتامينات',
  'dna': 'حمض نووي: حامل المعلومات الوراثية',
  'rna': 'حمض نووي ريبوزي: ينقل التعليمات وينتج البروتين',
  'cell': 'خلية: الوحدة الأساسية للحياة',
  'osmosis': 'انتشار: انتقال الماء عبر غشاء نصف منفذ',
  'diffusion': 'انتشار: انتقال الجزيئات من الأعلى تركيزًا للأقل',
  'photosynthesis': 'بناء ضوئي: نبات يصنع غذاءه من الضوء',
  'respiration': 'تنفس خلوي: إنتاج الطاقة من الغذاء',
  'metabolism': 'أيض: كل التفاعلات الحيوية في الجسم',
  'immune system': 'جهاز المناعة: يدافع عن الجسم ضد الممرضات',
  'antibody': 'جسم مضاد: بروتين يحارب مولدات الضد',
  'vaccine': 'لقاح: يدرّب المناعة على مرض معين',
  'allergy': 'حساسية: رد فعل مناعي ضد مادة غير ضارة',
  'antigen': 'مولد الضد: مادة يهاجمها الجهاز المناعي',
  'calorie': 'سعرة: وحدة قياس الطاقة في الغذاء',
  'nutrition': 'تغذية: ما يحتاجه الجسم من الغذاء',
  'vitamin': 'فيتامين: مادة عضوية يحتاجها الجسم بكميات صغيرة',
  'mineral': 'معدن: عنصر غير عضوي يحتاجه الجسم',
  'enzyme activity': 'نشاط الإنزيم: سرعة عمل الإنزيم حسب الحرارة والـ pH',
  'ph': 'مقياس الحموضة: من 0 (حمضي) إلى 14 (قاعدي)',
  'acid': 'حمض: مادة تزيد تركيز أيونات الهيدروجين',
  'base': 'قاعدة: مادة تزيد تركيز أيونات الهيدروكسيد',
  'solution': 'محلول: مادة مذابة في مذيب',
  'concentration': 'تركيز: كمية المادة في حجم معين',
  'mole': 'مول: وحدة عدّالجزيئات في الكيمياء',
  'force': 'قوة: تغيّر حركة الجسم أو شكله',
  'velocity': 'سرعة متجهة: التغير في الموضع مع الزمن',
  'acceleration': 'تسارع: تغير السرعة مع الزمن',
  'gravity': 'جاذبية: قوة جذب الأرض للأشياء',
  'energy': 'طاقة: القدرة على إنجاز شغل',
  'mass': 'كمية المادة في الجسم',
  'weight': 'وزن: قوة الجاذبية على الكتلة',
  'friction': 'احتكاك: قوة تعاكس الحركة بين السطوح',
  'momentum': 'كمية الحركة: الكتلة × السرعة',
  'algorithm': 'خوارزمية: خطوات مرتبة لحل مشكلة',
  'function': 'دالة: كود يستقبل مدخلات ويعيد ناتج',
  'variable': 'متغير: مكان لتخزين قيمة',
  'array': 'مصفوفة: قائمة منظمة من العناصر',
  'database': 'قاعدة بيانات: تخبيق منظم للبيانات',
  'api': 'واجهة برمجية: طريقة تواصل بين برنامجين',
  'server': 'خادم: جهاز يقدم خدمات لأجهزة أخرى',
  'network': 'شبكة: أجهزة متصلة لتبادل البيانات',
  'encryption': 'تشفير: تحويل البيانات لشكل غير مقروء إلا للمفتاح',
  'protocol': 'بروتوكول: قواعد تواصل متفق عليها',
  'loop': 'حلقة: تكرار خطوات في البرمجة',
  'recursion': 'استدعاء ذاتي: دالة تستدعي نفسها',
  'variable scope': 'نطاق المتغير: مكان الوصول إليه في الكود',
  'probability': 'احتمالية: احتمال وقوع حدث من 0 إلى 1',
  'statistics': 'إحصاء: تحليل البيانات وتفسيرها',
  'mean': 'المتوسط: مجموع القيم على عددها',
  'median': 'الوسيط: القيمة الوسطى بعد الترتيب',
  'standard deviation': 'الانحراف المعياري: تشتت القيم عن المتوسط',
  'derivative': 'اشتقاق: معدل تغير الدالة',
  'integral': 'تكامل: مساحة تحت المنحنى',
  'matrix': 'مصفوفة: جدول منظمة من الأرقام',
  'vector': 'متجه: كمية لها مقدار واتجاه',
  'hypothesis': 'فرضية: تخمين قابل للاختبار',
  'variable (science)': 'متغير: ما يتغير في التجربة',
  'control group': 'مجموعة ضابطة: بدون المعاملة للمقارنة',
  'peer review': 'مراجعة الأقران: تقييم العلماء لعملهم قبل النشر',
  'supply and demand': 'العرض والطلب: يحددان السعر',
  'inflation': 'تضخم: ارتفاع مستمر في الأسعار',
  'opportunity cost': 'تكلفة الفرصة البديلة: ما تتخلى عنه لاختيارك',
  'profit': 'ربح: الإيراد ناقص التكاليف',
  'revenue': 'إيراد: المال الوارد من المبيعات',
  'market share': 'حصة السوق: نسبة مبيعات الشركة من السوق',
  'stakeholder': 'صاحب مصلحة: يتأثر بقرارات الشركة',
  'entrepreneur': 'رائد أعمال: يبدأ مشروعًا بمخاطرة',
  'macroeconomics': 'اقتصاد كلي: يدرس الاقتصاد الوطني ككل',
  'microeconomics': 'اقتصاد جزئي: يدرس سلوك الأفراد والشركات',
  'law of demand': 'قانون الطلب: ارتفاع السعر ← انخفاض الطلب',
  'elasticity': 'مرونة: كم يستجيب الطلب لتغير السعر',
  'accounting': 'محاسبة: تسجيل وتحليل العمليات المالية',
  'balance sheet': 'ميزانية: الأصول = الالتزامات + حقوق الملكية',
  'cell division': 'انقسام الخلية: تكاثر الخلايا',
  'mitosis': 'انقسام متساوي: خلية مطابقة للأصل',
  'meiosis': 'انقسام نصفي: ينتج خلايا جنسية بنصف العدد',
  'chromosome': 'كروموسوم: حامل الجينات',
  'gene': 'جين: وحدة المعلومات الوراثية',
  'mutation': 'طفرة: تغيّر في تسلسل DNA',
  'natural selection': 'انتقاء طبيعي: الأصلح يبقى',
  'ecosystem': 'نظام بيئي: الكائنات مع بيئتها',
  'biodiversity': 'تنوع حيوي: تنوع الكائنات في منطقة',
  'food chain': 'سلسلة غذائية: من منتج إلى مستهلك',
  'digestion': 'هضم: تكسير الغذاء لامتصاصه',
  'circulatory system': 'جهاز الدوران: ينقل الدم في الجسم',
  'nervous system': 'جهاز العصب: ينقل الإشارات ويتحكم',
  'homeostasis': 'اتزان داخلي: ثبات ظروف الجسم الداخلية',
  'oxidation': 'أكسدة: فقدان الإلكترونات',
  'reduction': 'اختزال: كسب الإلكترونات',
  'combustion': 'احتراق: تفاعل مع الأكسجين يطلق حرارة',
  'polymer': 'بوليمر: جزيء كبير من وحدات متكررة',
  'catalyst': 'حفاز: يسرع التفاعل دون استهلاكه',
  'yield': 'ناتج التفاعل: كمية المنتج',
  'titration': 'محايدة: معرفة التركيز بتفاعل معروف',
  'buffer': 'محلول منظم: يقاوم تغير الحموضة',
  'kinetic energy': 'طاقة حركية: طاقة الحركة',
  'potential energy': 'طاقة كامنة: طاقة مخزنة بالموقع',
  'thermodynamics': ' الديناميكا الحرارية: دراسة الحرارة والطاقة',
  'entropy': 'إنتروبيا: درجة العشواء في النظام',
  'wave': 'موجة: اهتزاز ينقل الطاقة',
  'frequency': 'تردد: عدد الدورات في الثانية',
  'amplitude': 'سعة الموجة: أقصى إزاحة',
  'refraction': 'انكسار: انحراف الضوء عند تغيير الوسط',
  'current': 'تيار كهربي: تدفق الشحنة',
  'voltage': 'جهد كهربي: قوة دفع الشحنة',
  'resistance': 'مقاومة: تعند التيار الكهربي',
  'circuit': 'دائرة كهربية: مسار مغلق للتيار',
  'machine learning': 'تعلم آلة: أنظمة تتعلم من البيانات',
  'neural network': 'شبكة عصبية: نموذج مبني على الدماغ',
  'data structure': 'بنية بيانات: طريقة منظمة لتخزين البيانات',
  'object oriented programming': 'برمجة كائنية: بناء البرامج من كائنات',
  'compiler': 'مترجم: يحول الكود لشفرة آلة',
  'operating system': 'نظام تشغيل: يدير أجهزة وبرامج الكمبيوتر',
  'cloud computing': 'حوسبة سحابية: خدمات عبر الإنترنت',
  'user interface': 'واجهة المستخدم: ما يراه المستخدم ويتفاعل معه',
  'usability': 'سهولة الاستخدام: قدرة المستخدم على الإنجاز',
  'user experience': 'تجربة المستخدم: إحساسه أثناء الاستخدام',
  'accessibility': 'إتاحة: تمكن الجميع من الاستخدام',
  'prototype': 'نموذج أولي: نسخة تجريبية قابلة للاختبار',
  'design thinking': 'تصميم تفكيري: منهج حل المشكلات بالتصميم',
  'brand': 'علامة تجارية: هوية المنتج في ذهن العميل',
  'marketing': 'تسويق: إيصال المنتج للعميل',
  'customer segment': 'شريحة العملاء: فئة محددة نستهدفها',
  'value proposition': 'عرض القيمة: لماذا يختارك العميل',
  'cash flow': 'التدفق النقدي: حركة المال الداخل والخارج',
  'break-even': 'نقطة التعادل: حيث التكاليف = الإيرادات',
  'project management': 'إدارة المشاريع: تخطيط وتنفيذ وتسليم',
  'risk management': 'إدارة المخاطر: تحديد المخاطر والاستعداد لها',
  'stakeholder analysis': 'تحليل أصحاب المصلحة: من يتأثر بالمشروع',
  'gantt chart': 'مخطط جانت: جدول زمني للمهام',
  'milestone': 'معلم رئيسي: نقطة تقدم مهمة في المشروع',
}
